### ISSUE TITLE
conflict between  Obsidian Editing Toolbar and Obsidian Minimap

### ISSUE THREAD

**Issue by ksdavidc** [YairSegel/ObsidianMinimap#8]
Notice the big white space at top of minimap when [this plugin](https://github.com/PKM-er/obsidian-editing-toolbar) is installed:

<img width="796" height="337" alt="Image" src="https://github.com/user-attachments/assets/196a9616-a8f2-42ae-9bd5-89509c8e0125" />

Attached is sandbox vault. Sometimes you have to toggle the mode (reading, source, etc.) to see the problem.

[Minimap.zip](https://github.com/user-attachments/files/22323355/Minimap.zip)

SYSTEM INFO:
	Obsidian version: v1.9.12
	Installer version: v1.9.12
	Operating system: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64 23.6.0
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Editing Toolbar v3.1.18
		2: Note Minimap v1.0.0

**Comment by YairSegel** [comment]
I'm familiar the issue with long notes, trying to find a fix (see #6)...
I'll try to fix the top-offset soon - got a bit of mess in there currently 😅 
The toggle button issue should be fixed with 1.1.1

**Comment by ksdavidc** [comment]
I see. It sounds quite challenging. I hope it all gets worked out cause the minimap is very useful for me, especially on the long notes...

**Comment by YairSegel** [comment]
The long notes issue should be now fixed using Better Rendering (:
Working on the other things now...
Please let me know if you face any other issues!

**Comment by ksdavidc** [comment]
long notes still a problem as noted in a separate issue, though recent update is a big jump ahead. Keep going, it seems very close.
